spring:
  application:
    name: ledger

  datasource:
    url: jdbc:mysql://localhost:3306/ledger
    username: root
    password: 4615

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true